import './globals.css'
import { Press_Start_2P } from 'next/font/google'
const pres = Press_Start_2P({ 
  subsets: ['latin'],
  weight: ['400']
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pres.className}>
        {children}</body>
    </html>
  )
}
